只在Ubuntu20.04下存在的(Ubuntu16.04下不存在)涉及buildroot编译错误:
Q1. you need to install ·unbuffer·
A1. sudo apt install expect
Q2. gdbusauth.c:1305:11: error: ‘%s’ directive argument is null
A2. 修改 buildroot/output/rockchip_rk3399_recovery/build/host-libglib2-2.54.2/gio/gdbusauth.c line 1305 将 debug_print 挪到 'if (line == NULL) goto out;' 之后
Q3. gdbusmessage.c:2700:30: error: ‘%s’ directive argument is null
A3. 注释掉 buildroot/output/rockchip_rk3399_recovery/build/host-libglib2-2.54.2/gio/gdbusmessage.c line 2700
Q4. host-qemu-2.10.2/linux-user/syscall.c:259:16: error: static declaration of ‘gettid’ follows non-static declaration
A4. 注释掉 buildroot/output/rockchip_rk3399_recovery/build/host-qemu-2.10.2/linux-user/syscall.c line 259
Q5. host-qemu-2.10.2/linux-user/ioctls.h:173:9: error: ‘SIOCGSTAMP’ undeclared here (not in a function); did you mean ‘SIOCSRARP’?
A5. 注释掉 buildroot/output/rockchip_rk3399_recovery/build/host-qemu-2.10.2/linux-user/ioctls.h line 173
Q6. host-qemu-2.10.2/linux-user/ioctls.h:174:9: error: ‘SIOCGSTAMPNS’ undeclared here (not in a function); did you mean ‘SIOCGSTAMP_OLD’?
A6. 注释掉 buildroot/output/rockchip_rk3399_recovery/build/host-qemu-2.10.2/linux-user/ioctls.h line 174
(以上参考: https://blog.csdn.net/nicholas_duan/article/details/109063131)

ps: qt编译问题，在Ubuntu16.04也存在，解决方法： 注释掉 buildroot/configs/rockchip_rk3399_defconfig 中的 ·#include "qt.config"·